name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm i

      - name: Build
        run: npm run build

      - name: Push
        uses: actions-x/commit@v2
        with:
          email: 41898282+github-actions[bot]@users.noreply.github.com
          name: github-actions[bot]
          branch: main
          files: dist themes
          repository: https://github.com/PhongGuy/css-styles
          token: ${{ secrets.MY_SECRET_TOKEN }}
          message: automated regeneration